/**
 * Report generator.
 * Converts a ResearchResult into a formatted Markdown report.
 */

import type { ResearchResult } from './types';

export class ReportGenerator {
  /**
   * Generate a full Markdown research report.
   */
  generate(result: ResearchResult): string {
    const lines: string[] = [];

    lines.push(`# Deep Research Report: ${result.query}`);
    lines.push('');
    lines.push(`**Confidence:** ${(result.confidence * 100).toFixed(0)}%`);
    lines.push(`**Rounds completed:** ${result.rounds.length}`);
    lines.push(`**Sources found:** ${result.sources.length}`);
    lines.push(`**Saved to knowledge base:** ${result.savedToKnowledgeBase ? 'Yes' : 'No'}`);
    lines.push('');

    lines.push('---');
    lines.push('');
    lines.push('## Executive Summary');
    lines.push('');
    lines.push(result.synthesis);
    lines.push('');

    lines.push('---');
    lines.push('');
    lines.push('## Research Rounds');
    lines.push('');

    for (const round of result.rounds) {
      lines.push(this.generateRoundSection(round));
    }

    lines.push('---');
    lines.push('');
    lines.push('## Sources');
    lines.push('');

    for (const source of result.sources) {
      lines.push(`- **${source.title}** (${source.type})`);
      lines.push(`  - URL: ${source.url}`);
      lines.push(`  - Retrieved: ${source.retrievedAt}`);
      lines.push('');
    }

    lines.push('---');
    lines.push('');
    lines.push('*Report generated by Deep Research Engine*');

    return lines.join('\n');
  }

  /**
   * Generate a Markdown section for a single research round.
   */
  generateRoundSection(round: import('./types').ResearchRound): string {
    const lines: string[] = [];

    lines.push(`### Round ${round.round}`);
    lines.push('');

    lines.push('**Search queries:**');
    for (const q of round.searchQueries) {
      lines.push(`- \`${q}\``);
    }
    lines.push('');

    if (round.findings.length > 0) {
      lines.push('**Findings:**');
      lines.push('');
      for (const finding of round.findings) {
        lines.push(`- **${finding.title}** (relevance: ${finding.relevanceScore})`);
        lines.push(`  - ${finding.snippet}`);
        lines.push(`  - Source: [${finding.source.title}](${finding.url})`);
        lines.push('');
      }
    }

    if (round.newQuestions.length > 0) {
      lines.push('**New questions generated:**');
      for (const q of round.newQuestions) {
        lines.push(`- ${q}`);
      }
      lines.push('');
    }

    return lines.join('\n');
  }
}
